### ISSUE TITLE
No such file or directory, open '/github/workspace/.github/labels.json'

### ISSUE THREAD

**Issue by chrisblakley** [lannonbr/issue-label-manager-action#7]
I have created my labels.json file inside of the appropriate `/.github/` directory, but when I run the action, I get the following error message:

```
(node:1) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/github/workspace/.github/labels.json'
    at Object.openSync (fs.js:439:3)
    at Object.readFileSync (fs.js:344:35)
    at run (/index.js:15:33)
     at process._tickCallback (internal/process/next_tick.js:68:7)
```

It seems it is looking for the file in `/github/workspace/.github/labels.json` for some reason. Is it possible the `GITHUB_WORKSPACE` variable can be different for various repos? https://github.com/lannonbr/issue-label-manager-action/blob/master/index.js#L8-L12

**Comment by oalders** [comment]
This fixed the issue for me as well.  Might be helpful for the README to include this?

**Comment by lannonbr** [comment]
@oalders Definitely. If you're participating in Hacktoberfest starting tomorrow, I could happily accept a PR for this. you can technically do it whenever but if you want to participate in the event, PRs are only counted during October

**Comment by oalders** [comment]
@lannonbr I will do this tomorrow.  :)
